# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x07\n\x05\x45mpty\"\x1f\n\x0eSendOTPRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"/\n\x10VerifyOTPRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"A\n\x12\x41uthTokensResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t2\xe2\x02\n\x0b\x41uthService\x12\x36\n\x07SendOTP\x12\x14.auth.SendOTPRequest\x1a\x15.auth.MessageResponse\x12=\n\tVerifyOTP\x12\x16.auth.VerifyOTPRequest\x1a\x18.auth.AuthTokensResponse\x12\x43\n\x0cRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x18.auth.AuthTokensResponse\x12\x32\n\x0cPublicAccess\x12\x0b.auth.Empty\x1a\x15.auth.MessageResponse\x12\x30\n\nUserAccess\x12\x0b.auth.Empty\x1a\x15.auth.MessageResponse\x12\x31\n\x0b\x41\x64minAccess\x12\x0b.auth.Empty\x1a\x15.auth.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_SENDOTPREQUEST']._serialized_start=29
  _globals['_SENDOTPREQUEST']._serialized_end=60
  _globals['_VERIFYOTPREQUEST']._serialized_start=62
  _globals['_VERIFYOTPREQUEST']._serialized_end=109
  _globals['_REFRESHTOKENREQUEST']._serialized_start=111
  _globals['_REFRESHTOKENREQUEST']._serialized_end=155
  _globals['_MESSAGERESPONSE']._serialized_start=157
  _globals['_MESSAGERESPONSE']._serialized_end=191
  _globals['_AUTHTOKENSRESPONSE']._serialized_start=193
  _globals['_AUTHTOKENSRESPONSE']._serialized_end=258
  _globals['_AUTHSERVICE']._serialized_start=261
  _globals['_AUTHSERVICE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
